name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger only when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR merging into main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        run: |
          # Install Salesforce CLI using the official method
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sSL https://install.salesforce.com/sfdx-cli/install | bash

      - name: Authenticate with Salesforce
        run: |
          echo "Authenticating with Salesforce..."
          sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile assets/server.key --username ${{ secrets.SF_USERNAME }} --instanceurl https://login.salesforce.com

      - name: Deploy to Salesforce
        run: |
          echo "Deploying metadata to Salesforce..."
          sfdx force:source:deploy -p force-app --targetusername ${{ secrets.SF_USERNAME }} --checkonly

      - name: Run Apex Tests
        run: |
          echo "Running Apex tests..."
          sfdx force:apex:test:run --resultformat human --targetusername ${{ secrets.SF_USERNAME }}
